### ISSUE TITLE
Why not in Coffeescript?

### ISSUE THREAD

**Issue by L0une** [markdalgleish/bespoke.js#53]
Hello,

You've choose to use Jade for HTML and Stylus for CSS; why no CoffeeScript for JS?

Regards,
L0une

**Comment by markdalgleish** [comment]
I don't use CoffeeScript and don't know many who still do.

When writing a Bespoke presentation, I spend almost none of my time writing JavaScript, so it wouldn't offer any advantages.

Of course, since the generator leaves you with a gulpfile rather than abstracting it away, you're free to introduce CoffeeScript into your project.
